font_family JetBrainsMono Nerd Font
font_size 11.0

# Window
window_padding_width 10
hide_window_decoration yes

# Colors
background #11111b
foreground #cdd6f4

selection_background #bd93f9
selection_doreground #11111b

cursor #bd93f9
cursor_text_color #11111b

# Tabs
active_tab_background #bd93f9
active_tab_foreground #11111b
inactive_tab_background #1e1e2e
inactive_tab_foreground #585b70

# Transparency
background_opacity 0.88

