#! /bin/sh

setxkbmap -layout se &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          18

# Bordercolor
bspc config normal_border_color "#44475a"
bspc config focused_border_color "#bd93f9"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Start compositor

xsetroot -solid "#11111b"
pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &

pgrep -x polybar > /dev/null || polybar main &


feh --bg-fill ~/Pictures/wallpapers/wallhaven-3zkgwy.png



